db:
    image: mysql
    volumes:
        - /c/temp/database:/var/lib/mysql
    environment:
        - MYSQL_DATABASE=moneyapi
        - MYSQL_USER=root
        - MYSQL_ROOT_PASSWORD=passmysql
    ports: 
        - 3306:3306
    container_name: mysql_moneyapp